extends: spectral:oas

rules:
  info-contact: warn
  info-license: off
  info-description: warn
  
  operation-description: warn
  operation-operationId: error
  operation-operationId-unique: error
  operation-parameters-unique: error
  operation-2xx-response: warn
  
  operation-singular-tag: error
  operation-tag-defined: error
  
  component-name-unique: error
  
  no-ambiguous-paths: error
  no-http-verbs-in-paths: error
  no-identical-paths: error
  no-path-trailing-slash: warn
  paths-kebab-case: off
  
  no-unresolved-refs: error
  no-unused-components: warn
  
  no-empty-servers: warn
  no-server-trailing-slash: warn
  
  no-schema-type-mismatch: error
  no-required-schema-properties-undefined: error
  no-enum-type-mismatch: error
  
  no-invalid-media-type-examples: warn
  no-invalid-parameter-examples: warn
  no-invalid-schema-examples: warn